version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - convert
      - build:
          requires:
            - convert
      - run:
          requires:
            - build
      - deploy:
          requires:
            - run

jobs:
  convert:
    working_directory: ~/hugo.github.io
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: |
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: .
          paths:
            - content
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          command: |
            hugo
      - persist_to_workspace:
          root: .
          paths:
            - public

  run:
    working_directory: ~/hugo.github.io/public
    docker:
      - image: circleci/python:3.7.6
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          command: |
              docker ps
              cd public/
              python -m http.server 8000

  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
           - "SHA256:H1mhEh6iKrw9NGStMOx87qCdxkc/kIv9ZuH6q8p73uY winhtet1997@gmail.com"
      - checkout
      - run:
           name: Deploy
           command: |
             cd ..
             git config --global user.name ${GIT_USER_NAME}
             git config --global user.email ${GIT_USER_EMAIL}
             git clone https://github.com/winhtet-mlc/hugo.github.io.git
             ls
             cp -rp public/* hugo.github.io/
             cd hugo.github.io
             ls
             git remote set-url origin git@github.com:winhtet-mlc/hugo.github.io.git
             git add .
             git commit -m "Automated Deploy"
             git push origin HEAD:main
